import React from "react";
import Head from "next/head";

import cx from "classnames";

interface PageProps {
  className?: string;
}

const Page: React.FC<PageProps> = ({ children, className }) => {
  return (
    <div data-scroll-section>
      <Head>
        <title>Philip Obosi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <br />
      <br />
      <main className={className}>{children}</main>
    </div>
  );
};

export default Page;
